"""Regenerate the synthetic message files under ``samples/``.

    python scripts/make_samples.py

Everything written is invented: test BICs, a fixed list of fictional company
names, and IBANs generated so they pass the ``schwifty`` checksum. CLAUDE.md
forbids real customer data anywhere in this repository, and a fixed seed keeps
the files stable so a diff means a real change.
"""

from __future__ import annotations

import datetime as dt
import sys
from pathlib import Path

from hub_format import samples
from hub_format.samples import SampleOptions
from hub_model.flows import (
    MT103,
    MT202,
    MT202COV,
    PACS_008,
    PACS_009,
    PACS_009_COV,
)

ROOT = Path(__file__).resolve().parent.parent
SAMPLES = ROOT / "samples"

# Pinned so regenerating produces byte-identical files and a diff means a real
# change, not a new clock reading.
PINNED_DT = dt.datetime(2026, 9, 28, 10, 15, 2, tzinfo=dt.UTC)
PINNED_VALUE_DATE = "2026-09-28"


def _opts(**kwargs: object) -> SampleOptions:
    """Sample options with the timestamp and value date pinned."""
    return SampleOptions(
        value_date=PINNED_VALUE_DATE,
        creation_dt=PINNED_DT,
        **kwargs,  # type: ignore[arg-type]
    )


# (file stem, message type, options). One UETR per file, fixed by the seed.
CATALOGUE: list[tuple[str, str, SampleOptions]] = [
    (
        "pacs008_eur",
        PACS_008,
        _opts(
            seed=1001,
            currency="EUR",
            amount="1234.56",
            sender_bic="TESTGB2LXXX",
            receiver_bic="TESTDEFFXXX",
        ),
    ),
    (
        "pacs008_usd",
        PACS_008,
        _opts(
            seed=1002,
            currency="USD",
            amount="98765.43",
            sender_bic="TESTGB2LXXX",
            receiver_bic="TESTUS33XXX",
        ),
    ),
    (
        "pacs008_sanctions_hit",
        PACS_008,
        _opts(seed=1003, currency="EUR", amount="500000.00", sanctions_hit=True),
    ),
    ("pacs009_gbp", PACS_009, _opts(seed=1004, currency="GBP", amount="2500000.00")),
    ("pacs009cov_eur", PACS_009_COV, _opts(seed=1005, currency="EUR", amount="750000.00")),
    (
        "mt103_gbp",
        MT103,
        _opts(
            seed=2001,
            currency="GBP",
            amount="4321.00",
            sender_bic="TESTGB2LXXX",
            receiver_bic="TESTDEFFXXX",
        ),
    ),
    ("mt103_chf", MT103, _opts(seed=2002, currency="CHF", amount="15000.00")),
    ("mt202_usd", MT202, _opts(seed=2003, currency="USD", amount="3000000.00")),
    ("mt202cov_eur", MT202COV, _opts(seed=2004, currency="EUR", amount="850000.00")),
]

HEADER = (
    "# Synthetic sample. Generated by scripts/make_samples.py — do not hand-edit.\n"
    "# No real customer data: test BICs, fictional names, checksum-valid IBANs.\n"
)


def write(path: Path, data: bytes) -> None:
    path.write_bytes(data)
    print(f"  {path.relative_to(ROOT)}  ({len(data)} bytes)")


def main() -> int:
    SAMPLES.mkdir(parents=True, exist_ok=True)
    print(f"writing samples into {SAMPLES.relative_to(ROOT)}")

    index: list[str] = []
    for stem, msg_type, options in CATALOGUE:
        if msg_type.startswith("pacs"):
            app_hdr, document, payment = samples.make_mx(msg_type, options)
            write(SAMPLES / f"{stem}.xml", document)
            write(SAMPLES / f"{stem}.apphdr.xml", app_hdr)
            files = f"{stem}.xml + {stem}.apphdr.xml"
        else:
            text, payment = samples.make_mt(msg_type, options)
            write(SAMPLES / f"{stem}.fin", text.encode("utf-8"))
            files = f"{stem}.fin"

        amount = payment.interbank_settlement_amount
        index.append(
            f"| `{files}` | {msg_type} | {amount.currency} {amount.amount} | {payment.ref.uetr} |"
        )

    readme = SAMPLES / "README.md"
    readme.write_text(
        "# Sample messages\n\n"
        "Synthetic only. Regenerate with `python scripts/make_samples.py`; never\n"
        "hand-edit, and never add anything derived from real traffic.\n\n"
        "Test BICs (`TEST...`) are not issued to real institutions, the company\n"
        "names are invented, and every IBAN is generated to pass the mod-97\n"
        "checksum that `schwifty` enforces.\n\n"
        "Send one into the Hub with:\n\n"
        "```bash\n"
        "ess send --type pacs.008 --file samples/pacs008_eur.xml \\\n"
        "         --app-hdr samples/pacs008_eur.apphdr.xml\n"
        "ess send --type MT103 --file samples/mt103_gbp.fin\n"
        "```\n\n"
        "| Files | Message type | Amount | UETR |\n"
        "| --- | --- | --- | --- |\n" + "\n".join(index) + "\n",
        encoding="utf-8",
    )
    print(f"  {readme.relative_to(ROOT)}")
    print(f"{len(CATALOGUE)} samples written")
    return 0


if __name__ == "__main__":
    sys.exit(main())
